name: build php
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - php/**
jobs:
  push:
    name: "yolks:php_${{ matrix.tag }}"
    runs-on: dedcom-node
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '7.4'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./php
          file: ./php/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cobaltthread/yolks:php_${{ matrix.tag }}
            ghcr.io/parkervcp/yolks:php_${{ matrix.tag }}
